"""initial schema

Revision ID: 98ad41ac68af
Revises:
Create Date: 2026-10-01 03:19:14.049120
"""
import sqlalchemy as sa
from alembic import op

import himsat.db.models

revision = '98ad41ac68af'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('aois',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('name_ne', sa.String(length=200), nullable=False),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('created_at', himsat.db.models.UTCDateTime(timezone=True), nullable=False),
    sa.Column('geom', sa.Text(), nullable=True),
    sa.Column('min_lon', sa.Float(), nullable=True),
    sa.Column('min_lat', sa.Float(), nullable=True),
    sa.Column('max_lon', sa.Float(), nullable=True),
    sa.Column('max_lat', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('assets',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('external_id', sa.String(length=64), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('name_ne', sa.String(length=200), nullable=False),
    sa.Column('lon', sa.Float(), nullable=False),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('elevation_m', sa.Float(), nullable=True),
    sa.Column('attrs', sa.JSON(), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('external_id')
    )
    with op.batch_alter_table('assets', schema=None) as batch_op:
        batch_op.create_index('ix_assets_lonlat', ['lon', 'lat'], unique=False)

    op.create_table('pipeline_runs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('aoi_id', sa.String(length=64), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('started_at', himsat.db.models.UTCDateTime(timezone=True), nullable=False),
    sa.Column('finished_at', himsat.db.models.UTCDateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('stats', sa.JSON(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('subscribers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('org_type', sa.String(length=32), nullable=False),
    sa.Column('language', sa.String(length=8), nullable=False),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('webhook_url', sa.String(length=500), nullable=True),
    sa.Column('channels', sa.JSON(), nullable=False),
    sa.Column('min_level', sa.String(length=16), nullable=False),
    sa.Column('aoi_ids', sa.JSON(), nullable=False),
    sa.Column('site_ids', sa.JSON(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', himsat.db.models.UTCDateTime(timezone=True), nullable=False),
    sa.Column('geom', sa.Text(), nullable=True),
    sa.Column('min_lon', sa.Float(), nullable=True),
    sa.Column('min_lat', sa.Float(), nullable=True),
    sa.Column('max_lon', sa.Float(), nullable=True),
    sa.Column('max_lat', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scenes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('aoi_id', sa.String(length=64), nullable=False),
    sa.Column('sensor', sa.String(length=8), nullable=False),
    sa.Column('key', sa.String(length=128), nullable=False),
    sa.Column('acquired_at', himsat.db.models.UTCDateTime(timezone=True), nullable=False),
    sa.Column('platform', sa.String(length=32), nullable=False),
    sa.Column('relative_orbit', sa.Integer(), nullable=True),
    sa.Column('cloud_cover', sa.Float(), nullable=True),
    sa.Column('item_ids', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('stats', sa.JSON(), nullable=False),
    sa.Column('processed_at', himsat.db.models.UTCDateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['aoi_id'], ['aois.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('aoi_id', 'sensor', 'key')
    )
    op.create_table('sites',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('aoi_id', sa.String(length=64), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('name_ne', sa.String(length=200), nullable=False),
    sa.Column('lon', sa.Float(), nullable=False),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('elevation_m', sa.Float(), nullable=True),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('attrs', sa.JSON(), nullable=False),
    sa.Column('flow_path', sa.Text(), nullable=True),
    sa.Column('first_seen', himsat.db.models.UTCDateTime(timezone=True), nullable=True),
    sa.Column('last_seen', himsat.db.models.UTCDateTime(timezone=True), nullable=True),
    sa.Column('latest_level', sa.String(length=16), nullable=False),
    sa.Column('latest_score', sa.Float(), nullable=True),
    sa.Column('latest_assessed_at', himsat.db.models.UTCDateTime(timezone=True), nullable=True),
    sa.Column('created_at', himsat.db.models.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', himsat.db.models.UTCDateTime(timezone=True), nullable=False),
    sa.Column('geom', sa.Text(), nullable=True),
    sa.Column('min_lon', sa.Float(), nullable=True),
    sa.Column('min_lat', sa.Float(), nullable=True),
    sa.Column('max_lon', sa.Float(), nullable=True),
    sa.Column('max_lat', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['aoi_id'], ['aois.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    with op.batch_alter_table('sites', schema=None) as batch_op:
        batch_op.create_index('ix_sites_aoi_kind', ['aoi_id', 'kind'], unique=False)
        batch_op.create_index('ix_sites_bbox', ['min_lon', 'min_lat', 'max_lon', 'max_lat'], unique=False)

    op.create_table('change_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('aoi_id', sa.String(length=64), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('sensor', sa.String(length=8), nullable=False),
    sa.Column('detected_at', himsat.db.models.UTCDateTime(timezone=True), nullable=False),
    sa.Column('pre_at', himsat.db.models.UTCDateTime(timezone=True), nullable=True),
    sa.Column('lon', sa.Float(), nullable=False),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('area_m2', sa.Float(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('attrs', sa.JSON(), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=True),
    sa.Column('scene_key', sa.String(length=160), nullable=False),
    sa.Column('geom', sa.Text(), nullable=True),
    sa.Column('min_lon', sa.Float(), nullable=True),
    sa.Column('min_lat', sa.Float(), nullable=True),
    sa.Column('max_lon', sa.Float(), nullable=True),
    sa.Column('max_lat', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['aoi_id'], ['aois.id'], ),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('change_events', schema=None) as batch_op:
        batch_op.create_index('ix_events_aoi_time', ['aoi_id', 'detected_at'], unique=False)

    op.create_table('observations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('sensor', sa.String(length=8), nullable=False),
    sa.Column('scene_key', sa.String(length=160), nullable=False),
    sa.Column('observed_at', himsat.db.models.UTCDateTime(timezone=True), nullable=False),
    sa.Column('reference_at', himsat.db.models.UTCDateTime(timezone=True), nullable=True),
    sa.Column('values', sa.JSON(), nullable=False),
    sa.Column('quality', sa.Float(), nullable=False),
    sa.Column('method', sa.String(length=64), nullable=False),
    sa.Column('created_at', himsat.db.models.UTCDateTime(timezone=True), nullable=False),
    sa.Column('geom', sa.Text(), nullable=True),
    sa.Column('min_lon', sa.Float(), nullable=True),
    sa.Column('min_lat', sa.Float(), nullable=True),
    sa.Column('max_lon', sa.Float(), nullable=True),
    sa.Column('max_lat', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('site_id', 'kind', 'scene_key')
    )
    with op.batch_alter_table('observations', schema=None) as batch_op:
        batch_op.create_index('ix_obs_site_kind_time', ['site_id', 'kind', 'observed_at'], unique=False)

    op.create_table('risk_assessments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=False),
    sa.Column('assessed_at', himsat.db.models.UTCDateTime(timezone=True), nullable=False),
    sa.Column('level', sa.String(length=16), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('hazard', sa.Float(), nullable=False),
    sa.Column('exposure', sa.Float(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('indicators', sa.JSON(), nullable=False),
    sa.Column('reasons', sa.JSON(), nullable=False),
    sa.Column('model_version', sa.String(length=32), nullable=False),
    sa.Column('created_at', himsat.db.models.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('risk_assessments', schema=None) as batch_op:
        batch_op.create_index('ix_risk_site_time', ['site_id', 'assessed_at'], unique=False)

    op.create_table('site_exposures',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('path_distance_km', sa.Float(), nullable=False),
    sa.Column('offset_m', sa.Float(), nullable=False),
    sa.Column('height_above_channel_m', sa.Float(), nullable=False),
    sa.Column('travel_time_min', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('site_id', 'asset_id')
    )
    op.create_table('alerts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uid', sa.String(length=36), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=False),
    sa.Column('assessment_id', sa.Integer(), nullable=True),
    sa.Column('level', sa.String(length=16), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('issued_at', himsat.db.models.UTCDateTime(timezone=True), nullable=False),
    sa.Column('created_at', himsat.db.models.UTCDateTime(timezone=True), nullable=False),
    sa.Column('expires_at', himsat.db.models.UTCDateTime(timezone=True), nullable=True),
    sa.Column('approved_by', sa.String(length=100), nullable=True),
    sa.Column('approved_at', himsat.db.models.UTCDateTime(timezone=True), nullable=True),
    sa.Column('dispatched_at', himsat.db.models.UTCDateTime(timezone=True), nullable=True),
    sa.Column('title_en', sa.Text(), nullable=False),
    sa.Column('body_en', sa.Text(), nullable=False),
    sa.Column('sms_en', sa.Text(), nullable=False),
    sa.Column('title_ne', sa.Text(), nullable=False),
    sa.Column('body_ne', sa.Text(), nullable=False),
    sa.Column('sms_ne', sa.Text(), nullable=False),
    sa.Column('generator', sa.String(length=100), nullable=False),
    sa.Column('facts', sa.JSON(), nullable=False),
    sa.Column('validation', sa.JSON(), nullable=False),
    sa.Column('supersedes_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['assessment_id'], ['risk_assessments.id'], ),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['supersedes_id'], ['alerts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uid')
    )
    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.create_index('ix_alerts_site_time', ['site_id', 'created_at'], unique=False)

    op.create_table('deliveries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('alert_id', sa.Integer(), nullable=False),
    sa.Column('subscriber_id', sa.Integer(), nullable=False),
    sa.Column('channel', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('provider_ref', sa.String(length=200), nullable=True),
    sa.Column('sent_at', himsat.db.models.UTCDateTime(timezone=True), nullable=True),
    sa.Column('updated_at', himsat.db.models.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['alert_id'], ['alerts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subscriber_id'], ['subscribers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('alert_id', 'subscriber_id', 'channel')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('deliveries')
    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.drop_index('ix_alerts_site_time')

    op.drop_table('alerts')
    op.drop_table('site_exposures')
    with op.batch_alter_table('risk_assessments', schema=None) as batch_op:
        batch_op.drop_index('ix_risk_site_time')

    op.drop_table('risk_assessments')
    with op.batch_alter_table('observations', schema=None) as batch_op:
        batch_op.drop_index('ix_obs_site_kind_time')

    op.drop_table('observations')
    with op.batch_alter_table('change_events', schema=None) as batch_op:
        batch_op.drop_index('ix_events_aoi_time')

    op.drop_table('change_events')
    with op.batch_alter_table('sites', schema=None) as batch_op:
        batch_op.drop_index('ix_sites_bbox')
        batch_op.drop_index('ix_sites_aoi_kind')

    op.drop_table('sites')
    op.drop_table('scenes')
    op.drop_table('subscribers')
    op.drop_table('pipeline_runs')
    with op.batch_alter_table('assets', schema=None) as batch_op:
        batch_op.drop_index('ix_assets_lonlat')

    op.drop_table('assets')
    op.drop_table('aois')
    # ### end Alembic commands ###
