"""watch cell velocities

Revision ID: cdf468c2ea6f
Revises: 98ad41ac68af
Create Date: 2026-10-01 03:24:42.449276
"""
import sqlalchemy as sa
from alembic import op

import himsat.db.models

revision = 'cdf468c2ea6f'
down_revision = '98ad41ac68af'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cell_velocities',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('aoi_id', sa.String(length=64), nullable=False),
    sa.Column('cell', sa.String(length=16), nullable=False),
    sa.Column('pair_key', sa.String(length=160), nullable=False),
    sa.Column('pair_start', himsat.db.models.UTCDateTime(timezone=True), nullable=False),
    sa.Column('pair_end', himsat.db.models.UTCDateTime(timezone=True), nullable=False),
    sa.Column('orbit', sa.Integer(), nullable=True),
    sa.Column('v', sa.Float(), nullable=False),
    sa.Column('se', sa.Float(), nullable=False),
    sa.Column('n', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('aoi_id', 'cell', 'pair_key')
    )
    with op.batch_alter_table('cell_velocities', schema=None) as batch_op:
        batch_op.create_index('ix_cellvel_aoi_cell_time', ['aoi_id', 'cell', 'pair_end'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cell_velocities', schema=None) as batch_op:
        batch_op.drop_index('ix_cellvel_aoi_cell_time')

    op.drop_table('cell_velocities')
    # ### end Alembic commands ###
